[tool.pytest.ini_options]
testpaths = ["portal", "tests"]

[project]
name = "newlife-core-api"
version = "0.1.0"
description = "NewLife Core API Portal with core infrastructure"
authors = [{ name = "Jay Hsia", email = "jayhsia1997@gmail.com" }]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    # base
    "dependency-injector",
    "fastapi",
    "fastapi-limiter",
    "gunicorn>=25,<26",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    # db
    "asyncpg",
    "redis>=7,<8",
    "sqlalchemy",
    "psycopg2-binary",
    # security
    "pyjwt",
    "msal",
    "azure-identity",
    "azure-storage-blob",
    # microsoft graph
    "msgraph-beta-sdk",
    # utils
    "cryptography>=47,<48",
    "email-validator",
    "httpx",
    "pillow",
    "python-multipart",
    "ujson",
    "pytz",
    "python-dateutil",
    "pyyaml",
]

[dependency-groups]
dev = [
    "alembic",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "click",
]

[tool.uv]
package = false
required-version = ">=0.12.4,<0.13"
