"""
add facility rental_rate applicability
Revision ID: 4dc556afd7b4
Revises: 2e4a67829714
Create Date: 2026-07-15 15:21:59.290213
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc556afd7b4'
down_revision: Union[str, None] = '2e4a67829714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_rate', sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON applicability rule; null means always eligible'), schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_rate', 'applicability', schema='facility')
    # ### end Alembic commands ###
