"""
add facility room blackout
Revision ID: aa5c9c88de59
Revises: b2a237486622
Create Date: 2026-07-21 16:36:35.340196
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'aa5c9c88de59'
down_revision: Union[str, None] = 'b2a237486622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_blackout',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_id', sa.UUID(), nullable=True, comment='Room ID; NULL means all rooms (campus-wide)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Blackout label (admin)'),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='Required admin-only reason'),
    sa.Column('kind', sa.String(length=32), nullable=False, comment='one_off or recurring'),
    sa.Column('blackout_date', sa.Date(), nullable=True, comment='Local date for one_off blackouts'),
    sa.Column('days_of_week_mask', sa.SmallInteger(), nullable=True, comment='Bitmask of ISO weekdays for recurring blackouts: bit0=Monday(0) ... bit6=Sunday(6)'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Local start time'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Local end time'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='Seasonal effective start (inclusive), recurring'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Seasonal effective end (inclusive), recurring'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint("(kind = 'one_off' AND blackout_date IS NOT NULL AND days_of_week_mask IS NULL) OR (kind = 'recurring' AND blackout_date IS NULL AND days_of_week_mask IS NOT NULL AND (days_of_week_mask & 127) != 0 AND (days_of_week_mask & ~127) = 0)", name=op.f('ck_room_blackout_kind_shape')),
    sa.CheckConstraint("kind IN ('one_off', 'recurring')", name=op.f('ck_room_blackout_kind_valid')),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to', name=op.f('ck_room_blackout_effective_date_order')),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_room_blackout_start_before_end')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_room_blackout_facility_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_blackout')),
    schema='facility'
    )
    op.create_index('ix_room_blackout_facility_active', 'room_blackout', ['facility_id', 'is_active'], unique=False, schema='facility')
    op.create_index('ix_room_blackout_is_active', 'room_blackout', ['is_active'], unique=False, schema='facility')
    op.create_index('ix_room_blackout_kind_date', 'room_blackout', ['kind', 'blackout_date'], unique=False, schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_blackout_kind_date', table_name='room_blackout', schema='facility')
    op.drop_index('ix_room_blackout_is_active', table_name='room_blackout', schema='facility')
    op.drop_index('ix_room_blackout_facility_active', table_name='room_blackout', schema='facility')
    op.drop_table('room_blackout', schema='facility')
    # ### end Alembic commands ###
