"""
add content file tables
Revision ID: b2a237486622
Revises: 4dc556afd7b4
Create Date: 2026-07-19 22:11:33.338950
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b2a237486622'
down_revision: Union[str, None] = '4dc556afd7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS content")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename as uploaded'),
    sa.Column('key', sa.String(length=512), nullable=False, comment='Storage object key (path)'),
    sa.Column('storage', sa.String(length=16), nullable=False, comment='Storage backend, e.g., azure_blob, s3'),
    sa.Column('bucket', sa.String(length=128), nullable=False, comment='Container or bucket name'),
    sa.Column('region', sa.String(length=32), nullable=False, comment='Storage region'),
    sa.Column('content_type', sa.String(length=128), nullable=True, comment='MIME type'),
    sa.Column('extension', sa.String(length=16), nullable=True, comment='File extension'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='File size in bytes'),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True, comment='MD5 checksum'),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='SHA-256 checksum'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Image width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Image height in pixels'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Media duration in seconds'),
    sa.Column('status', sa.Integer(), nullable=False, comment='File status, refer to FileStatus enum'),
    sa.Column('version', sa.Integer(), nullable=False, comment='File version number'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether the file is public'),
    sa.Column('source', sa.Integer(), nullable=True, comment='Upload source, refer to FileUploadSource'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file')),
    sa.UniqueConstraint('bucket', 'key', name=op.f('uq_file_bucket_key')),
    schema='content'
    )
    op.create_index(op.f('ix_file_key'), 'file', ['key'], unique=False, schema='content')
    op.create_table('file_association',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='File ID'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
    sa.Column('resource_name', sa.String(length=32), nullable=False, comment='Resource name (default table name)'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.ForeignKeyConstraint(['file_id'], ['content.file.id'], name=op.f('fk_file_association_file_id_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_association')),
    schema='content'
    )
    op.create_index(op.f('ix_file_association_file_id'), 'file_association', ['file_id'], unique=False, schema='content')
    op.create_index(op.f('ix_file_association_resource_id'), 'file_association', ['resource_id'], unique=False, schema='content')
    op.create_index(op.f('ix_file_association_resource_name'), 'file_association', ['resource_name'], unique=False, schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_association_resource_name'), table_name='file_association', schema='content')
    op.drop_index(op.f('ix_file_association_resource_id'), table_name='file_association', schema='content')
    op.drop_index(op.f('ix_file_association_file_id'), table_name='file_association', schema='content')
    op.drop_table('file_association', schema='content')
    op.drop_index(op.f('ix_file_key'), table_name='file', schema='content')
    op.drop_table('file', schema='content')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS content")
