"""
Alter user_profile to replace preferred_language with preferred_locale_id, and add unique constraint to role_permission.
Revision ID: f2e4575c6a3e
Revises: ea7fb3945441
Create Date: 2026-04-28 23:25:30.661127
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f2e4575c6a3e'
down_revision: Union[str, None] = 'ea7fb3945441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_role_permission_role_id_permission_id'), 'role_permission', ['role_id', 'permission_id'], schema='auth')
    op.add_column('user_profile', sa.Column('preferred_locale_id', sa.UUID(), nullable=True, comment='Preferred locale ID'), schema='auth')
    op.create_index(op.f('ix_user_profile_preferred_locale_id'), 'user_profile', ['preferred_locale_id'], unique=False, schema='auth')
    op.create_foreign_key(op.f('fk_user_profile_preferred_locale_id_system_locale'), 'user_profile', 'system_locale', ['preferred_locale_id'], ['id'], source_schema='auth', referent_schema='public', ondelete='SET NULL')
    op.drop_column('user_profile', 'preferred_language', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('preferred_language', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Preferred language'), schema='auth')
    op.drop_constraint(op.f('fk_user_profile_preferred_locale_id_system_locale'), 'user_profile', schema='auth', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_preferred_locale_id'), table_name='user_profile', schema='auth')
    op.drop_column('user_profile', 'preferred_locale_id', schema='auth')
    op.drop_constraint(op.f('uq_role_permission_role_id_permission_id'), 'role_permission', schema='auth', type_='unique')
    # ### end Alembic commands ###
