"""
Initial schema for authentication and authorization system, including tables for users, rbac, auditing, and more.
Revision ID: ea7fb3945441
Revises:
Create Date: 2026-04-27 19:28:35.191415
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea7fb3945441'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('record_id', sa.UUID(), nullable=True, comment='Record ID in the audited table'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='Operation type string (OperationType.value). refer to libs.consts.enums.OperationType'),
    sa.Column('operation_code', sa.String(length=64), nullable=True, comment='Operation code(default use table name)'),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete old record data'),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete new record data'),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Only the fields that changed with old/new values'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent string'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log')),
    schema='audit'
    )
    op.create_table('resource',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('pid', sa.UUID(), nullable=True, comment='Parent resource id'),
    sa.Column('key', sa.String(length=128), nullable=False, comment='Resource key and front-end corresponding'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='Resource code (e.g., user, course, article)'),
    sa.Column('icon', sa.String(length=32), nullable=True, comment='Resource icon'),
    sa.Column('path', sa.String(length=256), nullable=True, comment='Resource path'),
    sa.Column('type', sa.Integer(), nullable=False, comment='Resource type, Enum: ResourceType'),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Is resource visible'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.ForeignKeyConstraint(['pid'], ['auth.resource.id'], name=op.f('fk_resource_pid_resource'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource')),
    sa.UniqueConstraint('code', name=op.f('uq_resource_code')),
    sa.UniqueConstraint('key', name=op.f('uq_resource_key')),
    schema='auth'
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='Role code'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is role active'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code')),
    schema='auth'
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email, unique identifier'),
    sa.Column('phone_number', sa.String(length=16), nullable=True, comment='Phone number, unique identifier'),
    sa.Column('password_hash', sa.String(length=512), nullable=True, comment='Password hash'),
    sa.Column('salt', sa.String(length=128), nullable=True, comment='Salt for password hash'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='Is verified'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Is superuser'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Is admin'),
    sa.Column('password_changed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password last changed time'),
    sa.Column('password_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password expiration time'),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last login'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_user_phone_number')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False, schema='auth')
    op.create_table('verb',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='Verb action (e.g., create, read, update, delete)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is verb active'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verb')),
    sa.UniqueConstraint('action', name=op.f('uq_verb_action')),
    schema='auth'
    )
    op.create_table('system_locale',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('language_code', sa.String(length=16), nullable=False, comment='Language code (e.g., en, zh, etc.)'),
    sa.Column('script_code', sa.String(length=16), nullable=True, comment='Script code (e.g., Latn, Hant, etc.)'),
    sa.Column('region_code', sa.String(length=16), nullable=True, comment='Region code (e.g., US, TW, etc.)'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Locale name'),
    sa.Column('native_name', sa.String(length=64), nullable=True, comment='Native locale name'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is locale active'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='Is default locale'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_locale')),
    sa.UniqueConstraint('language_code', 'script_code', 'region_code', name=op.f('uq_system_locale_language_code_script_code_region_code')),
    schema='public'
    )
    op.create_table('device',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='First seen at'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last seen at'),
    sa.Column('last_ip', sa.String(length=45), nullable=True, comment='Last IP'),
    sa.Column('last_user_agent', sa.String(length=512), nullable=True, comment='Last user agent'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_device_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_device_id_user_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False, schema='auth')
    op.create_table('permission',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
    sa.Column('verb_id', sa.UUID(), nullable=False, comment='Verb ID'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='Permission Code (e.g., user:read)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is permission active'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['resource_id'], ['auth.resource.id'], name=op.f('fk_permission_resource_id_resource'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verb_id'], ['auth.verb.id'], name=op.f('fk_permission_verb_id_verb'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_permission_code')),
    sa.UniqueConstraint('resource_id', 'verb_id', name=op.f('uq_permission_resource_id_verb_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_permission_resource_id'), 'permission', ['resource_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_permission_verb_id'), 'permission', ['verb_id'], unique=False, schema='auth')
    op.create_table('resource_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Resource name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_resource_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['auth.resource.id'], name=op.f('fk_resource_translation_resource_id_resource'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_translation')),
    sa.UniqueConstraint('resource_id', 'locale_id', name=op.f('uq_resource_translation_resource_id_locale_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_resource_translation_locale_id'), 'resource_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_resource_translation_resource_id'), 'resource_translation', ['resource_id'], unique=False, schema='auth')
    op.create_table('role_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Role name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_role_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_role_translation_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_translation')),
    sa.UniqueConstraint('role_id', 'locale_id', name=op.f('uq_role_translation_role_id_locale_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_role_translation_locale_id'), 'role_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_translation_role_id'), 'role_translation', ['role_id'], unique=False, schema='auth')
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('first_name', sa.String(length=64), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=64), nullable=False, comment='Last name'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='Title'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='Refer to Gender enum'),
    sa.Column('preferred_name', sa.String(length=64), nullable=True, comment='Preferred name'),
    sa.Column('preferred_language', sa.String(length=16), nullable=True, comment='Preferred language'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_user_profile_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True, schema='auth')
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_user_role_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_user_role_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False, schema='auth')
    op.create_table('user_third_party',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('provider', sa.String(length=16), nullable=False, comment='Provider name, Enum: ThirdPartyProvider'),
    sa.Column('provider_tenant_id', sa.UUID(), nullable=False, comment='Provider tenant ID'),
    sa.Column('provider_uid', sa.String(length=255), nullable=False, comment='Provider UID'),
    sa.Column('access_token', sa.String(length=255), nullable=True, comment='Access token'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='Refresh token'),
    sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Token expiration time'),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name='fk_user_third_party_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_third_party')),
    sa.UniqueConstraint('user_id', 'provider', 'provider_uid', name=op.f('uq_user_third_party_user_id_provider_provider_uid')),
    schema='auth'
    )
    op.create_index(op.f('ix_user_third_party_user_id'), 'user_third_party', ['user_id'], unique=False, schema='auth')
    op.create_table('verb_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('verb_id', sa.UUID(), nullable=False, comment='Verb ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Verb name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_verb_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verb_id'], ['auth.verb.id'], name=op.f('fk_verb_translation_verb_id_verb'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verb_translation')),
    sa.UniqueConstraint('verb_id', 'locale_id', name=op.f('uq_verb_translation_verb_id_locale_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_verb_translation_locale_id'), 'verb_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_verb_translation_verb_id'), 'verb_translation', ['verb_id'], unique=False, schema='auth')
    op.create_table('permission_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='Permission ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Permission name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_permission_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permission.id'], name=op.f('fk_permission_translation_permission_id_permission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_translation')),
    sa.UniqueConstraint('permission_id', 'locale_id', name=op.f('uq_permission_translation_permission_id_locale_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_permission_translation_locale_id'), 'permission_translation', ['locale_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_permission_translation_permission_id'), 'permission_translation', ['permission_id'], unique=False, schema='auth')
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('device_id', sa.UUID(), nullable=True, comment='Device ID'),
    sa.Column('family_id', sa.UUID(), nullable=False, comment='Family ID'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Parent ID'),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True, comment='Replaced by ID'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='Token hash'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expires at'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last used at'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Revoked at'),
    sa.Column('revoked_reason', sa.String(length=32), nullable=True, comment='Revoked reason'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['device_id'], ['auth.device.id'], name=op.f('fk_refresh_token_device_id_device'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth.refresh_token.id'], name=op.f('fk_refresh_token_parent_id_refresh_token'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['auth.refresh_token.id'], name=op.f('fk_refresh_token_replaced_by_id_refresh_token'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    schema='auth'
    )
    op.create_index(op.f('ix_refresh_token_device_id'), 'refresh_token', ['device_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_expires_at'), 'refresh_token', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_last_used_at'), 'refresh_token', ['last_used_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_parent_id'), 'refresh_token', ['parent_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_replaced_by_id'), 'refresh_token', ['replaced_by_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True, schema='auth')
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False, schema='auth')
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='Expiration time, can be used for temporary authorization'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permission.id'], name=op.f('fk_role_permission_permission_id_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permission_role_id_permission_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_role_permission_expire_date'), 'role_permission', ['expire_date'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission', schema='auth')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission', schema='auth')
    op.drop_index(op.f('ix_role_permission_expire_date'), table_name='role_permission', schema='auth')
    op.drop_table('role_permission', schema='auth')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_replaced_by_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_parent_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_last_used_at'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_expires_at'), table_name='refresh_token', schema='auth')
    op.drop_index(op.f('ix_refresh_token_device_id'), table_name='refresh_token', schema='auth')
    op.drop_table('refresh_token', schema='auth')
    op.drop_index(op.f('ix_permission_translation_permission_id'), table_name='permission_translation', schema='auth')
    op.drop_index(op.f('ix_permission_translation_locale_id'), table_name='permission_translation', schema='auth')
    op.drop_table('permission_translation', schema='auth')
    op.drop_index(op.f('ix_verb_translation_verb_id'), table_name='verb_translation', schema='auth')
    op.drop_index(op.f('ix_verb_translation_locale_id'), table_name='verb_translation', schema='auth')
    op.drop_table('verb_translation', schema='auth')
    op.drop_index(op.f('ix_user_third_party_user_id'), table_name='user_third_party', schema='auth')
    op.drop_table('user_third_party', schema='auth')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role', schema='auth')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role', schema='auth')
    op.drop_table('user_role', schema='auth')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile', schema='auth')
    op.drop_table('user_profile', schema='auth')
    op.drop_index(op.f('ix_role_translation_role_id'), table_name='role_translation', schema='auth')
    op.drop_index(op.f('ix_role_translation_locale_id'), table_name='role_translation', schema='auth')
    op.drop_table('role_translation', schema='auth')
    op.drop_index(op.f('ix_resource_translation_resource_id'), table_name='resource_translation', schema='auth')
    op.drop_index(op.f('ix_resource_translation_locale_id'), table_name='resource_translation', schema='auth')
    op.drop_table('resource_translation', schema='auth')
    op.drop_index(op.f('ix_permission_verb_id'), table_name='permission', schema='auth')
    op.drop_index(op.f('ix_permission_resource_id'), table_name='permission', schema='auth')
    op.drop_table('permission', schema='auth')
    op.drop_index(op.f('ix_device_user_id'), table_name='device', schema='auth')
    op.drop_table('device', schema='auth')
    op.drop_table('system_locale', schema='public')
    op.drop_table('verb', schema='auth')
    op.drop_index(op.f('ix_user_is_active'), table_name='user', schema='auth')
    op.drop_table('user', schema='auth')
    op.drop_table('role', schema='auth')
    op.drop_table('resource', schema='auth')
    op.drop_table('log', schema='audit')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS audit CASCADE;")
