"""
remove rental policy setting
Revision ID: 46812261fe47
Revises: 122205581ff0
Create Date: 2026-09-02 22:49:24.739437
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46812261fe47'
down_revision: Union[str, None] = '122205581ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_policy_setting_facility_id'), table_name='rental_policy_setting', schema='facility')
    op.drop_table('rental_policy_setting', schema='facility')
    op.alter_column('legal_document', 'effective_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_comment='Calendar day when current wording takes effect',
               existing_nullable=False,
               schema='content')
    op.alter_column('booking', 'quoted_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Quoted amount: line subtotals minus discount plus surcharges',
               existing_comment='Final quoted amount after floor rules',
               existing_nullable=True,
               schema='facility')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & 127) != 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & ~127) = 0', schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & 127) <> 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & (~ 127)) = 0', schema='org')
    op.alter_column('booking', 'quoted_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Final quoted amount after floor rules',
               existing_comment='Quoted amount: line subtotals minus discount plus surcharges',
               existing_nullable=True,
               schema='facility')
    op.alter_column('legal_document', 'effective_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_comment='Calendar day when current wording takes effect',
               existing_nullable=False,
               schema='content')
    op.create_table('rental_policy_setting',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), autoincrement=False, nullable=False, comment='Primary Key'),
    sa.Column('setting_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Setting key (RentalPolicySettingKey)'),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=True, comment='Room ID; NULL = global default'),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Setting amount or numeric value'),
    sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'CAD'::character varying"), autoincrement=False, nullable=False, comment='Currency code'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Create User ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Update User ID'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_rental_policy_setting_facility_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_policy_setting')),
    sa.UniqueConstraint('setting_key', 'facility_id', name=op.f('uq_rental_policy_setting_setting_key_facility_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='facility'
    )
    op.create_index(op.f('ix_rental_policy_setting_facility_id'), 'rental_policy_setting', ['facility_id'], unique=False, schema='facility')
    # ### end Alembic commands ###
