"""
add facility booking series
Revision ID: 69333500a240
Revises: ac46a70a08f9
Create Date: 2026-09-16 17:21:36.298061
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '69333500a240'
down_revision: Union[str, None] = 'ac46a70a08f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_series',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Booker user ID'),
    sa.Column('ministry_id', sa.UUID(), nullable=True, comment='Ministry reference (optional)'),
    sa.Column('first_occurrence_date', sa.Date(), nullable=False, comment='First weekly occurrence date (facility local)'),
    sa.Column('last_occurrence_date', sa.Date(), nullable=False, comment='Last weekly occurrence date (facility local)'),
    sa.Column('local_start_time', sa.Time(), nullable=False, comment='Shared local start time for every occurrence line'),
    sa.Column('local_end_time', sa.Time(), nullable=False, comment='Shared local end time for every occurrence line'),
    sa.Column('status', sa.String(length=32), server_default='pending_payment', nullable=False, comment='Series status'),
    sa.Column('payment_hold_expires_at', sa.DateTime(timezone=True), nullable=True, comment='When an unpaid Pending-payment Series hold expires'),
    sa.Column('billed_hours', sa.Numeric(precision=8, scale=2), nullable=True, comment='Sum of billed hours across occurrences'),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Series pre-discount subtotal'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Applied discount percent snapshot'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Series discount amount'),
    sa.Column('surcharge_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Series surcharge subtotal'),
    sa.Column('quoted_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Series payment total'),
    sa.Column('currency', sa.String(length=8), nullable=True, comment='Currency code aligned with rental rates'),
    sa.Column('is_mission_aligned', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Mission-aligned discount eligibility'),
    sa.Column('is_priority', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Priority Ministry snapshot at create'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint('last_occurrence_date >= first_occurrence_date', name=op.f('ck_booking_series_last_on_or_after_first')),
    sa.CheckConstraint('local_end_time > local_start_time', name=op.f('ck_booking_series_end_after_start')),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_booking_series_ministry_id_ministry'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_booking_series_user_id_user'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_series')),
    schema='facility'
    )
    op.create_index(op.f('ix_booking_series_ministry_id'), 'booking_series', ['ministry_id'], unique=False, schema='facility')
    op.create_index('ix_booking_series_payment_hold_expires_at', 'booking_series', ['payment_hold_expires_at'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_series_status'), 'booking_series', ['status'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_series_user_id'), 'booking_series', ['user_id'], unique=False, schema='facility')
    op.create_index('ix_booking_series_user_id_status', 'booking_series', ['user_id', 'status'], unique=False, schema='facility')
    op.add_column('booking', sa.Column('series_id', sa.UUID(), nullable=True, comment='Recurring Booking Series parent when this row is a Booking Occurrence'), schema='facility')
    op.create_index('ix_booking_series_id', 'booking', ['series_id'], unique=False, schema='facility')
    op.create_foreign_key(op.f('fk_booking_series_id_booking_series'), 'booking', 'booking_series', ['series_id'], ['id'], source_schema='facility', referent_schema='facility', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_booking_series_id_booking_series'), 'booking', schema='facility', type_='foreignkey')
    op.drop_index('ix_booking_series_id', table_name='booking', schema='facility')
    op.drop_column('booking', 'series_id', schema='facility')
    op.drop_index('ix_booking_series_user_id_status', table_name='booking_series', schema='facility')
    op.drop_index(op.f('ix_booking_series_user_id'), table_name='booking_series', schema='facility')
    op.drop_index(op.f('ix_booking_series_status'), table_name='booking_series', schema='facility')
    op.drop_index('ix_booking_series_payment_hold_expires_at', table_name='booking_series', schema='facility')
    op.drop_index(op.f('ix_booking_series_ministry_id'), table_name='booking_series', schema='facility')
    op.drop_table('booking_series', schema='facility')
    # ### end Alembic commands ###
