"""Add Booking Series Draft table

Revision ID: c4381f7f25af
Revises: a8795f38daa1
Create Date: 2026-09-18 22:53:27.252460
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4381f7f25af'
down_revision: Union[str, None] = 'a8795f38daa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_series_draft',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Creating member; only this user may read/edit'),
    sa.Column('title', sa.String(length=30), nullable=True, comment='Optional Booker-owned plain-text label before confirm'),
    sa.Column('ministry_id', sa.UUID(), nullable=True, comment='Ministry reference (optional)'),
    sa.Column('first_occurrence_date', sa.Date(), nullable=False, comment='First weekly occurrence date (facility local)'),
    sa.Column('last_occurrence_date', sa.Date(), nullable=False, comment='Last weekly occurrence date (facility local)'),
    sa.Column('local_start_time', sa.Time(), nullable=False, comment='Shared local start time for every occurrence line'),
    sa.Column('local_end_time', sa.Time(), nullable=False, comment='Shared local end time for every occurrence line'),
    sa.Column('is_mission_aligned', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Mission-aligned discount eligibility'),
    sa.Column('remark', sa.Text(), nullable=True, comment='Optional Booker remark'),
    sa.Column('surcharge_codes', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'"), nullable=False, comment='Selected surcharge codes'),
    sa.Column('excluded_dates', postgresql.ARRAY(sa.Date()), server_default=sa.text("'{}'"), nullable=False, comment='Permitted excluded occurrence dates'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.CheckConstraint('last_occurrence_date >= first_occurrence_date', name=op.f('ck_booking_series_draft_last_on_or_after_first')),
    sa.CheckConstraint('local_end_time > local_start_time', name=op.f('ck_booking_series_draft_end_after_start')),
    sa.CheckConstraint('title IS NULL OR (char_length(btrim(title)) >= 1 AND char_length(title) <= 30)', name=op.f('ck_booking_series_draft_title_length')),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_booking_series_draft_ministry_id_ministry'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_booking_series_draft_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_series_draft')),
    schema='facility'
    )
    op.create_index(op.f('ix_booking_series_draft_user_id'), 'booking_series_draft', ['user_id'], unique=False, schema='facility')
    op.create_table('booking_series_draft_room',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('series_draft_id', sa.UUID(), nullable=False, comment='Recurring Series Draft ID'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Selected room ID'),
    sa.Column('sequence', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Display order'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_series_draft_room_facility_id_room'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['series_draft_id'], ['facility.booking_series_draft.id'], name=op.f('fk_booking_series_draft_room_series_draft_id_booking_series_draft'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_series_draft_room')),
    schema='facility'
    )
    op.create_index('ix_booking_series_draft_room_series_draft_id', 'booking_series_draft_room', ['series_draft_id'], unique=False, schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_series_draft_room_series_draft_id', table_name='booking_series_draft_room', schema='facility')
    op.drop_table('booking_series_draft_room', schema='facility')
    op.drop_index(op.f('ix_booking_series_draft_user_id'), table_name='booking_series_draft', schema='facility')
    op.drop_table('booking_series_draft', schema='facility')
    # ### end Alembic commands ###
