"""
drop uq_booking_room_booking_facility
Revision ID: 122205581ff0
Revises: 0b9baccf516a
Create Date: 2026-09-02 20:01:21.550958
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '122205581ff0'
down_revision: Union[str, None] = '0b9baccf516a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_booking_room_booking_facility'), 'booking_room', schema='facility', type_='unique')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & 127) != 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & ~127) = 0', schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & 127) <> 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & (~ 127)) = 0', schema='org')
    op.create_unique_constraint(op.f('uq_booking_room_booking_facility'), 'booking_room', ['facility_booking_id', 'facility_id'], schema='facility', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
