"""
make org ministry_type_id nullable
Revision ID: 66fd53b703c7
Revises: 69333500a240
Create Date: 2026-09-17 15:09:35.798622
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '66fd53b703c7'
down_revision: Union[str, None] = '69333500a240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ministry', 'ministry_type_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Ministry type catalog ID',
               schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ministry', 'ministry_type_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Ministry type catalog ID',
               schema='org')
    # ### end Alembic commands ###
