"""
Add org, member and facility schemas
Revision ID: ca9cd1da49c4
Revises: f2e4575c6a3e
Create Date: 2026-06-30 12:10:27.434802
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ca9cd1da49c4'
down_revision: Union[str, None] = 'f2e4575c6a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS org")
    op.execute("CREATE SCHEMA IF NOT EXISTS member")
    op.execute("CREATE SCHEMA IF NOT EXISTS facility")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_discount_rule',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Discount code (RentalDiscountCode)'),
    sa.Column('percent_off', sa.Numeric(precision=5, scale=2), nullable=False, comment='Discount percent (e.g. 20.00, 30.00)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Policy description'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_discount_rule')),
    sa.UniqueConstraint('code', name=op.f('uq_rental_discount_rule_code')),
    schema='facility'
    )
    op.create_table('rental_surcharge',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Surcharge code (RentalSurchargeCode)'),
    sa.Column('charge_type', sa.String(length=32), nullable=False, comment='Charge type (RentalSurchargeChargeType)'),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Unit amount'),
    sa.Column('currency', sa.String(length=8), server_default='CAD', nullable=False, comment='Currency code'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('applies_to_booking_type', sa.String(length=32), nullable=True, comment='Optional booking type filter (e.g. one_time for deposit)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_surcharge')),
    sa.UniqueConstraint('code', name=op.f('uq_rental_surcharge_code')),
    schema='facility'
    )
    op.create_table('room',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Stable room code'),
    sa.Column('room_number', sa.String(length=16), nullable=True, comment='Physical room number (e.g. 124, G19)'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Capacity (persons)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag; inactive rooms cannot accept new bookings'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('code', name=op.f('uq_room_code')),
    schema='facility'
    )
    op.create_index(op.f('ix_room_is_active'), 'room', ['is_active'], unique=False, schema='facility')
    op.create_index('ix_room_is_active_sequence', 'room', ['is_active', 'sequence'], unique=False, schema='facility')
    op.create_table('person',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Linked auth user ID'),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Legal name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_person_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    schema='member'
    )
    op.create_index(op.f('ix_person_user_id'), 'person', ['user_id'], unique=True, schema='member')
    op.create_table('position',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Stable position code'),
    sa.Column('can_own_ministry', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this position can own a ministry'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position')),
    sa.UniqueConstraint('code', name=op.f('uq_position_code')),
    schema='org'
    )
    op.create_table('rental_policy_setting',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('setting_key', sa.String(length=64), nullable=False, comment='Setting key (RentalPolicySettingKey)'),
    sa.Column('facility_id', sa.UUID(), nullable=True, comment='Room ID; NULL = global default'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Setting amount or numeric value'),
    sa.Column('currency', sa.String(length=8), server_default='CAD', nullable=False, comment='Currency code'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_rental_policy_setting_facility_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_policy_setting')),
    sa.UniqueConstraint('setting_key', 'facility_id', name=op.f('uq_rental_policy_setting_setting_key_facility_id')),
    schema='facility'
    )
    op.create_index(op.f('ix_rental_policy_setting_facility_id'), 'rental_policy_setting', ['facility_id'], unique=False, schema='facility')
    op.create_table('rental_rate',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Room ID'),
    sa.Column('billing_unit', sa.String(length=32), server_default='hourly', nullable=False, comment='Billing unit (RentalRateBillingUnit)'),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Unit price'),
    sa.Column('currency', sa.String(length=8), server_default='CAD', nullable=False, comment='Currency code'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Fallback row for pricing (usually hourly)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='Price version effective start'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Price version effective end'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint('unit_amount >= 0', name=op.f('ck_rental_rate_unit_amount_non_negative')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_rental_rate_facility_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_rate')),
    sa.UniqueConstraint('facility_id', 'billing_unit', 'effective_from', name='uq_rental_rate_facility_unit_effective'),
    schema='facility'
    )
    op.create_index('ix_rental_rate_facility_active', 'rental_rate', ['facility_id', 'is_active'], unique=False, schema='facility')
    op.create_index(op.f('ix_rental_rate_facility_id'), 'rental_rate', ['facility_id'], unique=False, schema='facility')
    op.create_table('room_slot_template',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Room ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Template label (admin)'),
    sa.Column('days_of_week_mask', sa.SmallInteger(), nullable=False, comment='Bitmask of ISO weekdays: bit0=Monday(0) ... bit6=Sunday(6)'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Local start time'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Local end time'),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False, comment='Grid step in minutes (e.g. 60)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='Seasonal effective start (inclusive)'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Seasonal effective end (inclusive)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint('(days_of_week_mask & 127) != 0', name=op.f('ck_room_slot_template_days_of_week_mask_nonzero')),
    sa.CheckConstraint('(days_of_week_mask & ~127) = 0', name=op.f('ck_room_slot_template_days_of_week_mask_valid_bits')),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to', name=op.f('ck_room_slot_template_effective_date_order')),
    sa.CheckConstraint('slot_duration_minutes > 0', name=op.f('ck_room_slot_template_slot_duration_positive')),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_room_slot_template_start_before_end')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_room_slot_template_facility_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_slot_template')),
    schema='facility'
    )
    op.create_index('ix_room_slot_template_facility_active', 'room_slot_template', ['facility_id', 'is_active'], unique=False, schema='facility')
    op.create_index('ix_room_slot_template_facility_id', 'room_slot_template', ['facility_id'], unique=False, schema='facility')
    op.create_table('room_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('room_id', sa.UUID(), nullable=False, comment='Room ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Localized room name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_room_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['facility.room.id'], name=op.f('fk_room_translation_room_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_translation')),
    sa.UniqueConstraint('room_id', 'locale_id', name=op.f('uq_room_translation_room_id_locale_id')),
    schema='facility'
    )
    op.create_index(op.f('ix_room_translation_locale_id'), 'room_translation', ['locale_id'], unique=False, schema='facility')
    op.create_index(op.f('ix_room_translation_room_id'), 'room_translation', ['room_id'], unique=False, schema='facility')
    op.create_table('ministry',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('owner_position_id', sa.UUID(), nullable=True, comment='Owning leadership position'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='Ministry lifecycle status'),
    sa.Column('has_priority_booking', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Priority booking flag'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='Submitted for approval at'),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True, comment='User who submitted for approval'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approved at'),
    sa.Column('approved_by_id', sa.UUID(), nullable=True, comment='User who approved'),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True, comment='Rejected at'),
    sa.Column('rejected_by_id', sa.UUID(), nullable=True, comment='User who rejected'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment='Rejection reason'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Application creator user ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['auth.user.id'], name=op.f('fk_ministry_approved_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth.user.id'], name=op.f('fk_ministry_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_position_id'], ['org.position.id'], name=op.f('fk_ministry_owner_position_id_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['auth.user.id'], name=op.f('fk_ministry_rejected_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['auth.user.id'], name=op.f('fk_ministry_submitted_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_owner_position_id'), 'ministry', ['owner_position_id'], unique=False, schema='org')
    op.create_index(op.f('ix_ministry_status'), 'ministry', ['status'], unique=False, schema='org')
    op.create_index('ix_ministry_status_is_active', 'ministry', ['status', 'is_active'], unique=False, schema='org')
    op.create_table('position_assignment',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('position_id', sa.UUID(), nullable=False, comment='Position ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Incumbent user ID'),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Assignment start'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='Assignment end; null = current'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], name=op.f('fk_position_assignment_position_id_position'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_position_assignment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_assignment')),
    schema='org'
    )
    op.create_index(op.f('ix_position_assignment_position_id'), 'position_assignment', ['position_id'], unique=False, schema='org')
    op.create_index('ix_position_assignment_position_id_end_at', 'position_assignment', ['position_id', 'end_at'], unique=False, schema='org')
    op.create_index(op.f('ix_position_assignment_user_id'), 'position_assignment', ['user_id'], unique=False, schema='org')
    op.create_table('position_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('position_id', sa.UUID(), nullable=False, comment='Position ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('team', sa.String(length=128), nullable=False, comment='PositionTeam enum code'),
    sa.Column('office', sa.String(length=64), nullable=False, comment='PositionOffice enum code'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Localized position name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_position_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['org.position.id'], name=op.f('fk_position_translation_position_id_position'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_translation')),
    sa.UniqueConstraint('position_id', 'locale_id', name=op.f('uq_position_translation_position_id_locale_id')),
    schema='org'
    )
    op.create_index(op.f('ix_position_translation_locale_id'), 'position_translation', ['locale_id'], unique=False, schema='org')
    op.create_index(op.f('ix_position_translation_position_id'), 'position_translation', ['position_id'], unique=False, schema='org')
    op.create_table('booking',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Booker user ID'),
    sa.Column('facility_id', sa.UUID(), nullable=True, comment='Optional primary room for list filters; multi-room lines use booking_room'),
    sa.Column('ministry_id', sa.UUID(), nullable=True, comment='Ministry reference (optional)'),
    sa.Column('booking_type', sa.String(length=32), nullable=False, comment='Booking type (BookingType)'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='Booking start (UTC)'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='Booking end (UTC)'),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True, comment='iCal RRULE string (RFC 5545); series anchor is start_at'),
    sa.Column('recurrence_end_at', sa.DateTime(timezone=True), nullable=True, comment='Recurrence series end'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='Booking status (BookingStatus)'),
    sa.Column('is_mission_aligned', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Mission-aligned discount eligibility (PDF section 4c)'),
    sa.Column('billed_hours', sa.Numeric(precision=8, scale=2), nullable=True, comment='Total billed hours snapshot'),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Pre-discount subtotal snapshot'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Applied discount percent snapshot (0/20/30)'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Discount amount snapshot'),
    sa.Column('surcharge_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Surcharge subtotal snapshot'),
    sa.Column('quoted_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Final quoted amount after floor rules'),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Deposit amount snapshot (not collected in this phase)'),
    sa.Column('currency', sa.String(length=8), nullable=True, comment='Currency code aligned with rental rates'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Cancellation timestamp'),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True, comment='User who cancelled the booking'),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True, comment='Cancellation reason'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_booking_end_after_start')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['auth.user.id'], name=op.f('fk_booking_cancelled_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_facility_id_room'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_booking_ministry_id_ministry'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_booking_user_id_user'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking')),
    schema='facility'
    )
    op.create_index(op.f('ix_booking_facility_id'), 'booking', ['facility_id'], unique=False, schema='facility')
    op.create_index('ix_booking_facility_id_start_at', 'booking', ['facility_id', 'start_at'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_ministry_id'), 'booking', ['ministry_id'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_status'), 'booking', ['status'], unique=False, schema='facility')
    op.create_index('ix_booking_status_start_at', 'booking', ['status', 'start_at'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False, schema='facility')
    op.create_index('ix_booking_user_id_status', 'booking', ['user_id', 'status'], unique=False, schema='facility')
    op.create_table('rental_rate_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('rental_rate_id', sa.UUID(), nullable=False, comment='Rental rate ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_rental_rate_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_rate_id'], ['facility.rental_rate.id'], name=op.f('fk_rental_rate_translation_rental_rate_id_rental_rate'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_rate_translation')),
    sa.UniqueConstraint('rental_rate_id', 'locale_id', name=op.f('uq_rental_rate_translation_rental_rate_id_locale_id')),
    schema='facility'
    )
    op.create_index(op.f('ix_rental_rate_translation_locale_id'), 'rental_rate_translation', ['locale_id'], unique=False, schema='facility')
    op.create_index(op.f('ix_rental_rate_translation_rental_rate_id'), 'rental_rate_translation', ['rental_rate_id'], unique=False, schema='facility')
    op.create_table('ministry_approval',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_id', sa.UUID(), nullable=False, comment='Ministry ID'),
    sa.Column('owner_position_id', sa.UUID(), nullable=True, comment='Snapshot of owner position at submission'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending / approved / rejected'),
    sa.Column('requested_by_id', sa.UUID(), nullable=True, comment='Applicant user ID'),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True, comment='Approver user ID'),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True, comment='Decision timestamp'),
    sa.Column('comment', sa.String(length=500), nullable=True, comment='Approval comment'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_ministry_approval_ministry_id_ministry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_position_id'], ['org.position.id'], name=op.f('fk_ministry_approval_owner_position_id_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['auth.user.id'], name=op.f('fk_ministry_approval_requested_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['auth.user.id'], name=op.f('fk_ministry_approval_resolved_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_approval')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_approval_ministry_id'), 'ministry_approval', ['ministry_id'], unique=False, schema='org')
    op.create_index('ix_ministry_approval_ministry_id_status', 'ministry_approval', ['ministry_id', 'status'], unique=False, schema='org')
    op.create_table('ministry_member',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_id', sa.UUID(), nullable=False, comment='Ministry ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('member_role', sa.String(length=32), nullable=False, comment='primary or secondary'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_ministry_member_ministry_id_ministry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_ministry_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_member')),
    sa.UniqueConstraint('ministry_id', 'user_id', name=op.f('uq_ministry_member_ministry_id_user_id')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_member_ministry_id'), 'ministry_member', ['ministry_id'], unique=False, schema='org')
    op.create_index(op.f('ix_ministry_member_user_id'), 'ministry_member', ['user_id'], unique=False, schema='org')
    op.create_table('ministry_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_id', sa.UUID(), nullable=False, comment='Ministry ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Localized ministry name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_ministry_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_ministry_translation_ministry_id_ministry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_translation')),
    sa.UniqueConstraint('ministry_id', 'locale_id', name=op.f('uq_ministry_translation_ministry_id_locale_id')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_translation_locale_id'), 'ministry_translation', ['locale_id'], unique=False, schema='org')
    op.create_index(op.f('ix_ministry_translation_ministry_id'), 'ministry_translation', ['ministry_id'], unique=False, schema='org')
    op.create_table('booking_override_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_booking_id', sa.UUID(), nullable=False, comment='Override target booking ID'),
    sa.Column('overridden_booking_id', sa.UUID(), nullable=True, comment='Overridden booking ID'),
    sa.Column('overridden_by_id', sa.UUID(), nullable=False, comment='User who performed the override'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Room ID (denormalized for admin filters)'),
    sa.Column('outcome', sa.String(length=32), nullable=False, comment='Override outcome (OverrideOutcome)'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='Override reason'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.ForeignKeyConstraint(['facility_booking_id'], ['facility.booking.id'], name=op.f('fk_booking_override_log_facility_booking_id_booking'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_override_log_facility_id_room'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['overridden_booking_id'], ['facility.booking.id'], name=op.f('fk_booking_override_log_overridden_booking_id_booking'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['auth.user.id'], name=op.f('fk_booking_override_log_overridden_by_id_user'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_override_log')),
    schema='facility'
    )
    op.create_index('ix_booking_override_log_created_at', 'booking_override_log', ['created_at'], unique=False, schema='facility')
    op.create_index(op.f('ix_booking_override_log_facility_booking_id'), 'booking_override_log', ['facility_booking_id'], unique=False, schema='facility')
    op.create_index('ix_booking_override_log_facility_id_created_at', 'booking_override_log', ['facility_id', 'created_at'], unique=False, schema='facility')
    op.create_index('ix_booking_override_log_overridden_by_id', 'booking_override_log', ['overridden_by_id'], unique=False, schema='facility')
    op.create_table('booking_room',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_booking_id', sa.UUID(), nullable=False, comment='Booking ID'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Selected room ID'),
    sa.Column('sequence', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Display order'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='Room interval start (UTC)'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='Room interval end (UTC)'),
    sa.Column('billed_hours', sa.Numeric(precision=8, scale=2), nullable=True, comment='Billed hours for this room line'),
    sa.Column('pricing_tier_used', sa.String(length=32), nullable=True, comment='Pricing tier used (hourly or daily_flat)'),
    sa.Column('rental_rate_id', sa.UUID(), nullable=True, comment='Applied rental rate row'),
    sa.Column('line_subtotal', sa.Numeric(precision=12, scale=2), nullable=True, comment='Pre-discount room line subtotal'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_booking_room_end_after_start')),
    sa.ForeignKeyConstraint(['facility_booking_id'], ['facility.booking.id'], name=op.f('fk_booking_room_facility_booking_id_booking'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_room_facility_id_room'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['rental_rate_id'], ['facility.rental_rate.id'], name=op.f('fk_booking_room_rental_rate_id_rental_rate'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_room')),
    sa.UniqueConstraint('facility_booking_id', 'facility_id', name='uq_booking_room_booking_facility'),
    schema='facility'
    )
    op.create_index('ix_booking_room_booking_id', 'booking_room', ['facility_booking_id'], unique=False, schema='facility')
    op.create_index('ix_booking_room_facility_id', 'booking_room', ['facility_id'], unique=False, schema='facility')
    op.create_table('booking_slot',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_booking_id', sa.UUID(), nullable=False, comment='Booking ID'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Room ID (denormalized for queries)'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='Slot start (UTC)'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='Slot end (UTC)'),
    sa.Column('status', sa.String(length=32), server_default='confirmed', nullable=False, comment='Slot status (BookingSlotStatus)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_booking_slot_end_after_start')),
    sa.ForeignKeyConstraint(['facility_booking_id'], ['facility.booking.id'], name=op.f('fk_booking_slot_facility_booking_id_booking'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_slot_facility_id_room'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_slot')),
    schema='facility'
    )
    op.create_index('ix_booking_slot_booking_id', 'booking_slot', ['facility_booking_id'], unique=False, schema='facility')
    op.create_index('ix_booking_slot_facility_id_start_at_end_at', 'booking_slot', ['facility_id', 'start_at', 'end_at'], unique=False, schema='facility')
    op.create_table('booking_surcharge',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('facility_booking_id', sa.UUID(), nullable=False, comment='Booking ID'),
    sa.Column('rental_surcharge_id', sa.UUID(), nullable=False, comment='Rental surcharge catalog ID'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Quantity (hours or programs)'),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Unit amount snapshot'),
    sa.Column('line_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Line amount snapshot'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.ForeignKeyConstraint(['facility_booking_id'], ['facility.booking.id'], name=op.f('fk_booking_surcharge_facility_booking_id_booking'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_surcharge_id'], ['facility.rental_surcharge.id'], name=op.f('fk_booking_surcharge_rental_surcharge_id_rental_surcharge'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_surcharge')),
    schema='facility'
    )
    op.create_index(op.f('ix_booking_surcharge_facility_booking_id'), 'booking_surcharge', ['facility_booking_id'], unique=False, schema='facility')
    op.add_column('user', sa.Column('person_id', sa.UUID(), nullable=True, comment='Linked member person ID'), schema='auth')
    op.add_column('user', sa.Column('account_kind', sa.String(length=32), nullable=True, comment='Account kind: member, guest, external, service'), schema='auth')
    op.create_index(op.f('ix_user_person_id'), 'user', ['person_id'], unique=True, schema='auth')
    op.create_foreign_key(op.f('fk_user_person_id_person'), 'user', 'person', ['person_id'], ['id'], source_schema='auth', referent_schema='member', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_person_id_person'), 'user', schema='auth', type_='foreignkey')
    op.drop_index(op.f('ix_user_person_id'), table_name='user', schema='auth')
    op.drop_column('user', 'account_kind', schema='auth')
    op.drop_column('user', 'person_id', schema='auth')
    op.drop_index(op.f('ix_booking_surcharge_facility_booking_id'), table_name='booking_surcharge', schema='facility')
    op.drop_table('booking_surcharge', schema='facility')
    op.drop_index('ix_booking_slot_facility_id_start_at_end_at', table_name='booking_slot', schema='facility')
    op.drop_index('ix_booking_slot_booking_id', table_name='booking_slot', schema='facility')
    op.drop_table('booking_slot', schema='facility')
    op.drop_index('ix_booking_room_facility_id', table_name='booking_room', schema='facility')
    op.drop_index('ix_booking_room_booking_id', table_name='booking_room', schema='facility')
    op.drop_table('booking_room', schema='facility')
    op.drop_index('ix_booking_override_log_overridden_by_id', table_name='booking_override_log', schema='facility')
    op.drop_index('ix_booking_override_log_facility_id_created_at', table_name='booking_override_log', schema='facility')
    op.drop_index(op.f('ix_booking_override_log_facility_booking_id'), table_name='booking_override_log', schema='facility')
    op.drop_index('ix_booking_override_log_created_at', table_name='booking_override_log', schema='facility')
    op.drop_table('booking_override_log', schema='facility')
    op.drop_index(op.f('ix_ministry_translation_ministry_id'), table_name='ministry_translation', schema='org')
    op.drop_index(op.f('ix_ministry_translation_locale_id'), table_name='ministry_translation', schema='org')
    op.drop_table('ministry_translation', schema='org')
    op.drop_index(op.f('ix_ministry_member_user_id'), table_name='ministry_member', schema='org')
    op.drop_index(op.f('ix_ministry_member_ministry_id'), table_name='ministry_member', schema='org')
    op.drop_table('ministry_member', schema='org')
    op.drop_index('ix_ministry_approval_ministry_id_status', table_name='ministry_approval', schema='org')
    op.drop_index(op.f('ix_ministry_approval_ministry_id'), table_name='ministry_approval', schema='org')
    op.drop_table('ministry_approval', schema='org')
    op.drop_index(op.f('ix_rental_rate_translation_rental_rate_id'), table_name='rental_rate_translation', schema='facility')
    op.drop_index(op.f('ix_rental_rate_translation_locale_id'), table_name='rental_rate_translation', schema='facility')
    op.drop_table('rental_rate_translation', schema='facility')
    op.drop_index('ix_booking_user_id_status', table_name='booking', schema='facility')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking', schema='facility')
    op.drop_index('ix_booking_status_start_at', table_name='booking', schema='facility')
    op.drop_index(op.f('ix_booking_status'), table_name='booking', schema='facility')
    op.drop_index(op.f('ix_booking_ministry_id'), table_name='booking', schema='facility')
    op.drop_index('ix_booking_facility_id_start_at', table_name='booking', schema='facility')
    op.drop_index(op.f('ix_booking_facility_id'), table_name='booking', schema='facility')
    op.drop_table('booking', schema='facility')
    op.drop_index(op.f('ix_position_translation_position_id'), table_name='position_translation', schema='org')
    op.drop_index(op.f('ix_position_translation_locale_id'), table_name='position_translation', schema='org')
    op.drop_table('position_translation', schema='org')
    op.drop_index(op.f('ix_position_assignment_user_id'), table_name='position_assignment', schema='org')
    op.drop_index('ix_position_assignment_position_id_end_at', table_name='position_assignment', schema='org')
    op.drop_index(op.f('ix_position_assignment_position_id'), table_name='position_assignment', schema='org')
    op.drop_table('position_assignment', schema='org')
    op.drop_index('ix_ministry_status_is_active', table_name='ministry', schema='org')
    op.drop_index(op.f('ix_ministry_status'), table_name='ministry', schema='org')
    op.drop_index(op.f('ix_ministry_owner_position_id'), table_name='ministry', schema='org')
    op.drop_table('ministry', schema='org')
    op.drop_index(op.f('ix_room_translation_room_id'), table_name='room_translation', schema='facility')
    op.drop_index(op.f('ix_room_translation_locale_id'), table_name='room_translation', schema='facility')
    op.drop_table('room_translation', schema='facility')
    op.drop_index('ix_room_slot_template_facility_id', table_name='room_slot_template', schema='facility')
    op.drop_index('ix_room_slot_template_facility_active', table_name='room_slot_template', schema='facility')
    op.drop_table('room_slot_template', schema='facility')
    op.drop_index(op.f('ix_rental_rate_facility_id'), table_name='rental_rate', schema='facility')
    op.drop_index('ix_rental_rate_facility_active', table_name='rental_rate', schema='facility')
    op.drop_table('rental_rate', schema='facility')
    op.drop_index(op.f('ix_rental_policy_setting_facility_id'), table_name='rental_policy_setting', schema='facility')
    op.drop_table('rental_policy_setting', schema='facility')
    op.drop_table('position', schema='org')
    op.drop_index(op.f('ix_person_user_id'), table_name='person', schema='member')
    op.drop_table('person', schema='member')
    op.drop_index('ix_room_is_active_sequence', table_name='room', schema='facility')
    op.drop_index(op.f('ix_room_is_active'), table_name='room', schema='facility')
    op.drop_table('room', schema='facility')
    op.drop_table('rental_surcharge', schema='facility')
    op.drop_table('rental_discount_rule', schema='facility')
    # ### end Alembic commands ###
    op.execute("CREATE SCHEMA IF NOT EXISTS facility")
    op.execute("CREATE SCHEMA IF NOT EXISTS member")
    op.execute("CREATE SCHEMA IF NOT EXISTS org")
