"""
add legal document tables
Revision ID: 1e4cd2cdd4b6
Revises: 339faef3af01
Create Date: 2026-08-26 14:06:42.689470
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1e4cd2cdd4b6'
down_revision: Union[str, None] = '339faef3af01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_document',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('product', sa.String(length=64), nullable=False, comment='Built-in Product code'),
    sa.Column('kind', sa.String(length=64), nullable=False, comment='Legal Document Kind'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_document')),
    sa.UniqueConstraint('product', 'kind', name=op.f('uq_legal_document_product_kind')),
    schema='content'
    )
    op.create_index('ix_legal_document_product_kind_deleted', 'legal_document', ['product', 'kind', 'is_deleted'], unique=False, schema='content')
    op.create_table('legal_document_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('legal_document_id', sa.UUID(), nullable=False, comment='Legal Document ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('body', sa.Text(), server_default=sa.text("''"), nullable=False, comment='Markdown body'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['legal_document_id'], ['content.legal_document.id'], name=op.f('fk_legal_document_translation_legal_document_id_legal_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_legal_document_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_document_translation')),
    sa.UniqueConstraint('legal_document_id', 'locale_id', name=op.f('uq_legal_document_translation_legal_document_id_locale_id')),
    schema='content'
    )
    op.create_index(op.f('ix_legal_document_translation_legal_document_id'), 'legal_document_translation', ['legal_document_id'], unique=False, schema='content')
    op.create_index(op.f('ix_legal_document_translation_locale_id'), 'legal_document_translation', ['locale_id'], unique=False, schema='content')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & 127) != 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & ~127) = 0', schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & 127) <> 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & (~ 127)) = 0', schema='org')
    op.drop_index(op.f('ix_legal_document_translation_locale_id'), table_name='legal_document_translation', schema='content')
    op.drop_index(op.f('ix_legal_document_translation_legal_document_id'), table_name='legal_document_translation', schema='content')
    op.drop_table('legal_document_translation', schema='content')
    op.drop_index('ix_legal_document_product_kind_deleted', table_name='legal_document', schema='content')
    op.drop_table('legal_document', schema='content')
    # ### end Alembic commands ###
