"""
add ministry type target audience schedule
Revision ID: 2e4a67829714
Revises: ca9cd1da49c4
Create Date: 2026-07-10 13:45:25.108346
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2e4a67829714'
down_revision: Union[str, None] = 'ca9cd1da49c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministry_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Stable ministry type code'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_type')),
    sa.UniqueConstraint('code', name=op.f('uq_ministry_type_code')),
    schema='org'
    )
    op.create_table('target_audience',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='Stable target audience code'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_audience')),
    sa.UniqueConstraint('code', name=op.f('uq_target_audience_code')),
    schema='org'
    )
    op.create_table('ministry_type_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_type_id', sa.UUID(), nullable=False, comment='Ministry type ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Localized ministry type name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_ministry_type_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ministry_type_id'], ['org.ministry_type.id'], name=op.f('fk_ministry_type_translation_ministry_type_id_ministry_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_type_translation')),
    sa.UniqueConstraint('ministry_type_id', 'locale_id', name=op.f('uq_ministry_type_translation_ministry_type_id_locale_id')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_type_translation_locale_id'), 'ministry_type_translation', ['locale_id'], unique=False, schema='org')
    op.create_index(op.f('ix_ministry_type_translation_ministry_type_id'), 'ministry_type_translation', ['ministry_type_id'], unique=False, schema='org')
    op.create_table('target_audience_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('target_audience_id', sa.UUID(), nullable=False, comment='Target audience ID'),
    sa.Column('locale_id', sa.UUID(), nullable=False, comment='Locale ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Localized target audience name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.ForeignKeyConstraint(['locale_id'], ['public.system_locale.id'], name=op.f('fk_target_audience_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_audience_id'], ['org.target_audience.id'], name=op.f('fk_target_audience_translation_target_audience_id_target_audience'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_audience_translation')),
    sa.UniqueConstraint('target_audience_id', 'locale_id', name=op.f('uq_target_audience_translation_target_audience_id_locale_id')),
    schema='org'
    )
    op.create_index(op.f('ix_target_audience_translation_locale_id'), 'target_audience_translation', ['locale_id'], unique=False, schema='org')
    op.create_index(op.f('ix_target_audience_translation_target_audience_id'), 'target_audience_translation', ['target_audience_id'], unique=False, schema='org')
    op.create_table('ministry_schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_id', sa.UUID(), nullable=False, comment='Ministry ID'),
    sa.Column('days_of_week_mask', sa.SmallInteger(), nullable=True, comment='Bitmask of ISO weekdays: bit0=Monday(0) ... bit6=Sunday(6)'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='Local start time'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='Local end time'),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='Seasonal effective start (inclusive)'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Seasonal effective end (inclusive)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'),
    sa.CheckConstraint('days_of_week_mask IS NULL OR (days_of_week_mask & 127) != 0', name=op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero')),
    sa.CheckConstraint('days_of_week_mask IS NULL OR (days_of_week_mask & ~127) = 0', name=op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits')),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to', name=op.f('ck_ministry_schedule_ministry_schedule_effective_date_order')),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR start_time < end_time', name=op.f('ck_ministry_schedule_ministry_schedule_start_before_end')),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_ministry_schedule_ministry_id_ministry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_schedule')),
    schema='org'
    )
    op.create_index('ix_ministry_schedule_ministry_id', 'ministry_schedule', ['ministry_id'], unique=False, schema='org')
    op.create_table('ministry_target_audience',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('ministry_id', sa.UUID(), nullable=False, comment='Ministry ID'),
    sa.Column('target_audience_id', sa.UUID(), nullable=False, comment='Target audience ID'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_ministry_target_audience_ministry_id_ministry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_audience_id'], ['org.target_audience.id'], name=op.f('fk_ministry_target_audience_target_audience_id_target_audience'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_target_audience')),
    sa.UniqueConstraint('ministry_id', 'target_audience_id', name=op.f('uq_ministry_target_audience_ministry_id_target_audience_id')),
    schema='org'
    )
    op.create_index(op.f('ix_ministry_target_audience_ministry_id'), 'ministry_target_audience', ['ministry_id'], unique=False, schema='org')
    op.create_index(op.f('ix_ministry_target_audience_target_audience_id'), 'ministry_target_audience', ['target_audience_id'], unique=False, schema='org')
    op.add_column('ministry', sa.Column('ministry_type_id', sa.UUID(), nullable=False, comment='Ministry type catalog ID'), schema='org')
    op.create_index(op.f('ix_ministry_ministry_type_id'), 'ministry', ['ministry_type_id'], unique=False, schema='org')
    op.create_foreign_key(op.f('fk_ministry_ministry_type_id_ministry_type'), 'ministry', 'ministry_type', ['ministry_type_id'], ['id'], source_schema='org', referent_schema='org', ondelete='RESTRICT')
    op.add_column('ministry_member', sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Public contact email override'), schema='org')
    op.add_column('ministry_translation', sa.Column('schedule_note', sa.String(length=500), nullable=True, comment='Schedule supplement note per locale'), schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ministry_translation', 'schedule_note', schema='org')
    op.drop_column('ministry_member', 'contact_email', schema='org')
    op.drop_constraint(op.f('fk_ministry_ministry_type_id_ministry_type'), 'ministry', schema='org', type_='foreignkey')
    op.drop_index(op.f('ix_ministry_ministry_type_id'), table_name='ministry', schema='org')
    op.drop_column('ministry', 'ministry_type_id', schema='org')
    op.drop_index(op.f('ix_ministry_target_audience_target_audience_id'), table_name='ministry_target_audience', schema='org')
    op.drop_index(op.f('ix_ministry_target_audience_ministry_id'), table_name='ministry_target_audience', schema='org')
    op.drop_table('ministry_target_audience', schema='org')
    op.drop_index('ix_ministry_schedule_ministry_id', table_name='ministry_schedule', schema='org')
    op.drop_table('ministry_schedule', schema='org')
    op.drop_index(op.f('ix_target_audience_translation_target_audience_id'), table_name='target_audience_translation', schema='org')
    op.drop_index(op.f('ix_target_audience_translation_locale_id'), table_name='target_audience_translation', schema='org')
    op.drop_table('target_audience_translation', schema='org')
    op.drop_index(op.f('ix_ministry_type_translation_ministry_type_id'), table_name='ministry_type_translation', schema='org')
    op.drop_index(op.f('ix_ministry_type_translation_locale_id'), table_name='ministry_type_translation', schema='org')
    op.drop_table('ministry_type_translation', schema='org')
    op.drop_table('target_audience', schema='org')
    op.drop_table('ministry_type', schema='org')
    # ### end Alembic commands ###
