"""
add booking and series title
Revision ID: a8795f38daa1
Revises: 66fd53b703c7
Create Date: 2026-09-18 01:09:30.512728
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a8795f38daa1'
down_revision: Union[str, None] = '66fd53b703c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('title', sa.String(length=30), nullable=False, comment='Booker-owned plain-text label'), schema='facility')
    op.create_check_constraint(op.f('ck_booking_title_length'), 'booking', 'char_length(btrim(title)) >= 1 AND char_length(title) <= 30', schema='facility')
    op.add_column('booking_series', sa.Column('title', sa.String(length=30), nullable=False, comment='Booker-owned plain-text label'), schema='facility')
    op.create_check_constraint(op.f('ck_booking_series_title_length'), 'booking_series', 'char_length(btrim(title)) >= 1 AND char_length(title) <= 30', schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_booking_series_title_length'), 'booking_series', schema='facility', type_='check')
    op.drop_column('booking_series', 'title', schema='facility')
    op.drop_constraint(op.f('ck_booking_title_length'), 'booking', schema='facility', type_='check')
    op.drop_column('booking', 'title', schema='facility')
    # ### end Alembic commands ###
