"""
add effective date field to legal document table
Revision ID: 0b9baccf516a
Revises: 1e4cd2cdd4b6
Create Date: 2026-08-27 10:01:27.376666
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0b9baccf516a'
down_revision: Union[str, None] = '1e4cd2cdd4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_document', sa.Column('effective_date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE'), comment='Calendar day when current wording takes effect'), schema='content')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & 127) != 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask & ~127) = 0', schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_valid_bits'), 'ministry_schedule', schema='org', type_='check')
    op.drop_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mask_nonzero'), 'ministry_schedule', schema='org', type_='check')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_6c43'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & 127) <> 0', schema='org')
    op.create_check_constraint(op.f('ck_ministry_schedule_ministry_schedule_days_of_week_mas_1547'), 'ministry_schedule', 'days_of_week_mask IS NULL OR (days_of_week_mask::integer & (~ 127)) = 0', schema='org')
    op.drop_column('legal_document', 'effective_date', schema='content')
    # ### end Alembic commands ###
