"""
Add system setting table
Revision ID: 339faef3af01
Revises: f55bfce06859
Create Date: 2026-07-27 21:10:45.794154
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '339faef3af01'
down_revision: Union[str, None] = 'f55bfce06859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('namespace', sa.String(length=64), nullable=False, comment='Setting namespace'),
    sa.Column('setting_key', sa.String(length=64), nullable=False, comment='Setting key within namespace'),
    sa.Column('value_type', sa.String(length=32), nullable=False, comment='Declared value type (SettingValueType)'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON value matching value_type'),
    sa.Column('is_built_in', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Built-in settings cannot be deleted'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_setting')),
    sa.UniqueConstraint('namespace', 'setting_key', name=op.f('uq_system_setting_namespace_setting_key')),
    schema='public'
    )
    op.create_index(op.f('ix_system_setting_is_active'), 'system_setting', ['is_active'], unique=False, schema='public')
    op.create_index('ix_system_setting_namespace_key_active', 'system_setting', ['namespace', 'setting_key', 'is_active'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_setting_namespace_key_active', table_name='system_setting', schema='public')
    op.drop_index(op.f('ix_system_setting_is_active'), table_name='system_setting', schema='public')
    op.drop_table('system_setting', schema='public')
    # ### end Alembic commands ###
