"""
facility rental rate room binding and booking room rule snapshot
Revision ID: f55bfce06859
Revises: aa5c9c88de59
Create Date: 2026-07-27 18:55:15.044871
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f55bfce06859'
down_revision: Union[str, None] = 'aa5c9c88de59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_rate_template',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('billing_unit', sa.String(length=32), server_default='hourly', nullable=False, comment='Billing unit (RentalRateBillingUnit)'),
    sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON applicability rule; null means always eligible'),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Default / global unit price'),
    sa.Column('currency', sa.String(length=8), server_default='CAD', nullable=False, comment='Currency code'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Fallback template for pricing'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Active flag'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.CheckConstraint('unit_amount >= 0', name=op.f('ck_rental_rate_template_template_unit_amount_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_rate_template')),
    sa.UniqueConstraint('name', name='uq_rental_rate_template_name'),
    schema='facility'
    )
    op.create_index('ix_rental_rate_template_is_active', 'rental_rate_template', ['is_active'], unique=False, schema='facility')
    op.drop_index(op.f('ix_rental_rate_translation_locale_id'), table_name='rental_rate_translation', schema='facility')
    op.drop_index(op.f('ix_rental_rate_translation_rental_rate_id'), table_name='rental_rate_translation', schema='facility')
    op.drop_table('rental_rate_translation', schema='facility')
    op.add_column('booking_room', sa.Column('rental_rate_name', sa.String(length=255), nullable=True, comment='Snapshot: rule display name'), schema='facility')
    op.add_column('booking_room', sa.Column('billing_unit', sa.String(length=32), nullable=True, comment='Snapshot: billing unit used'), schema='facility')
    op.add_column('booking_room', sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Snapshot: unit amount used'), schema='facility')
    op.add_column('booking_room', sa.Column('currency', sa.String(length=8), nullable=True, comment='Snapshot: currency used'), schema='facility')
    op.add_column('booking_room', sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot: applicability rule used'), schema='facility')
    op.add_column('booking_room', sa.Column('is_default', sa.Boolean(), nullable=True, comment='Snapshot: whether rule was marked default'), schema='facility')
    op.drop_constraint(op.f('fk_booking_room_rental_rate_id_rental_rate'), 'booking_room', schema='facility', type_='foreignkey')
    op.drop_column('booking_room', 'pricing_tier_used', schema='facility')
    op.drop_column('booking_room', 'rental_rate_id', schema='facility')
    op.add_column('rental_rate', sa.Column('template_id', sa.UUID(), nullable=False, comment='Rate template ID'), schema='facility')
    op.drop_constraint(op.f('uq_rental_rate_facility_unit_effective'), 'rental_rate', schema='facility', type_='unique')
    op.create_index('ix_rental_rate_template_id', 'rental_rate', ['template_id'], unique=False, schema='facility')
    op.create_unique_constraint('uq_rental_rate_facility_template', 'rental_rate', ['facility_id', 'template_id'], schema='facility')
    op.create_foreign_key(op.f('fk_rental_rate_template_id_rental_rate_template'), 'rental_rate', 'rental_rate_template', ['template_id'], ['id'], source_schema='facility', referent_schema='facility', ondelete='RESTRICT')
    op.drop_column('rental_rate', 'is_default', schema='facility')
    op.drop_column('rental_rate', 'sequence', schema='facility')
    op.drop_column('rental_rate', 'effective_to', schema='facility')
    op.drop_column('rental_rate', 'applicability', schema='facility')
    op.drop_column('rental_rate', 'effective_from', schema='facility')
    op.drop_column('rental_rate', 'unit_amount', schema='facility')
    op.drop_column('rental_rate', 'currency', schema='facility')
    op.drop_column('rental_rate', 'billing_unit', schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_rate', sa.Column('billing_unit', sa.VARCHAR(length=32), server_default=sa.text("'hourly'::character varying"), autoincrement=False, nullable=False, comment='Billing unit (RentalRateBillingUnit)'), schema='facility')
    op.add_column('rental_rate', sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'CAD'::character varying"), autoincrement=False, nullable=False, comment='Currency code'), schema='facility')
    op.add_column('rental_rate', sa.Column('unit_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Unit price'), schema='facility')
    op.add_column('rental_rate', sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=True, comment='Price version effective start'), schema='facility')
    op.add_column('rental_rate', sa.Column('applicability', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON applicability rule; null means always eligible'), schema='facility')
    op.add_column('rental_rate', sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True, comment='Price version effective end'), schema='facility')
    op.add_column('rental_rate', sa.Column('sequence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('EXTRACT(epoch FROM now())'), autoincrement=False, nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'), schema='facility')
    op.add_column('rental_rate', sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Fallback row for pricing (usually hourly)'), schema='facility')
    op.drop_constraint(op.f('fk_rental_rate_template_id_rental_rate_template'), 'rental_rate', schema='facility', type_='foreignkey')
    op.drop_constraint('uq_rental_rate_facility_template', 'rental_rate', schema='facility', type_='unique')
    op.drop_index('ix_rental_rate_template_id', table_name='rental_rate', schema='facility')
    op.create_unique_constraint(op.f('uq_rental_rate_facility_unit_effective'), 'rental_rate', ['facility_id', 'billing_unit', 'effective_from'], schema='facility', postgresql_nulls_not_distinct=False)
    op.drop_column('rental_rate', 'template_id', schema='facility')
    op.add_column('booking_room', sa.Column('rental_rate_id', sa.UUID(), autoincrement=False, nullable=True, comment='Applied rental rate row'), schema='facility')
    op.add_column('booking_room', sa.Column('pricing_tier_used', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='Pricing tier used (hourly or daily_flat)'), schema='facility')
    op.create_foreign_key(op.f('fk_booking_room_rental_rate_id_rental_rate'), 'booking_room', 'rental_rate', ['rental_rate_id'], ['id'], source_schema='facility', referent_schema='facility', ondelete='SET NULL')
    op.drop_column('booking_room', 'is_default', schema='facility')
    op.drop_column('booking_room', 'applicability', schema='facility')
    op.drop_column('booking_room', 'currency', schema='facility')
    op.drop_column('booking_room', 'unit_amount', schema='facility')
    op.drop_column('booking_room', 'billing_unit', schema='facility')
    op.drop_column('booking_room', 'rental_rate_name', schema='facility')
    op.create_table('rental_rate_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), autoincrement=False, nullable=False, comment='Primary Key'),
    sa.Column('rental_rate_id', sa.UUID(), autoincrement=False, nullable=False, comment='Rental rate ID'),
    sa.Column('locale_id', sa.UUID(), autoincrement=False, nullable=False, comment='Locale ID'),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Display name'),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Create User ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Update User ID'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Update User Name'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Description'),
    sa.Column('remark', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['locale_id'], ['system_locale.id'], name=op.f('fk_rental_rate_translation_locale_id_system_locale'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_rate_id'], ['facility.rental_rate.id'], name=op.f('fk_rental_rate_translation_rental_rate_id_rental_rate'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_rate_translation')),
    sa.UniqueConstraint('rental_rate_id', 'locale_id', name=op.f('uq_rental_rate_translation_rental_rate_id_locale_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='facility'
    )
    op.create_index(op.f('ix_rental_rate_translation_rental_rate_id'), 'rental_rate_translation', ['rental_rate_id'], unique=False, schema='facility')
    op.create_index(op.f('ix_rental_rate_translation_locale_id'), 'rental_rate_translation', ['locale_id'], unique=False, schema='facility')
    op.drop_index('ix_rental_rate_template_is_active', table_name='rental_rate_template', schema='facility')
    op.drop_table('rental_rate_template', schema='facility')
    # ### end Alembic commands ###
