"""
add booking draft tables
Revision ID: ac46a70a08f9
Revises: 46812261fe47
Create Date: 2026-09-14 14:58:04.288447
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ac46a70a08f9'
down_revision: Union[str, None] = '46812261fe47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_draft',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Creating member; only this user may read/edit'),
    sa.Column('date', sa.Date(), nullable=False, comment='Local calendar day common to all lines'),
    sa.Column('ministry_id', sa.UUID(), nullable=True, comment='Ministry reference (optional)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.ForeignKeyConstraint(['ministry_id'], ['org.ministry.id'], name=op.f('fk_booking_draft_ministry_id_ministry'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], name=op.f('fk_booking_draft_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_draft')),
    schema='facility'
    )
    op.create_index(op.f('ix_booking_draft_user_id'), 'booking_draft', ['user_id'], unique=False, schema='facility')
    op.create_table('booking_draft_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False, comment='Primary Key'),
    sa.Column('booking_draft_id', sa.UUID(), nullable=False, comment='Booking Draft ID'),
    sa.Column('facility_id', sa.UUID(), nullable=False, comment='Selected room ID'),
    sa.Column('sequence', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Display order'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='Line interval start (UTC)'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='Line interval end (UTC)'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_booking_draft_line_end_after_start')),
    sa.ForeignKeyConstraint(['booking_draft_id'], ['facility.booking_draft.id'], name=op.f('fk_booking_draft_line_booking_draft_id_booking_draft'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.room.id'], name=op.f('fk_booking_draft_line_facility_id_room'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_draft_line')),
    schema='facility'
    )
    op.create_index('ix_booking_draft_line_booking_draft_id', 'booking_draft_line', ['booking_draft_id'], unique=False, schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_draft_line_booking_draft_id', table_name='booking_draft_line', schema='facility')
    op.drop_table('booking_draft_line', schema='facility')
    op.drop_index(op.f('ix_booking_draft_user_id'), table_name='booking_draft', schema='facility')
    op.drop_table('booking_draft', schema='facility')
    # ### end Alembic commands ###
