"""
add title to booking draft table
Revision ID: 8d433234107e
Revises: c4381f7f25af
Create Date: 2026-09-19 15:01:34.236794
--------------------------------------------------
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8d433234107e'
down_revision: Union[str, None] = 'c4381f7f25af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_draft', sa.Column('title', sa.String(length=30), nullable=False, comment='Booker-owned plain-text label'), schema='facility')
    op.create_check_constraint(op.f('ck_booking_draft_title_length'), 'booking_draft', 'char_length(btrim(title)) >= 1 AND char_length(title) <= 30', schema='facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_booking_draft_title_length'), 'booking_draft', schema='facility', type_='check')
    op.drop_column('booking_draft', 'title', schema='facility')
    # ### end Alembic commands ###
